LibraryProject/LibraryProject/Controllers/BranchController.cs
using System.Linq;
using LibraryData;
using LibraryProject.Models.Branch;
using Microsoft.AspNetCore.Mvc;

namespace LibraryProject.Controllers
{
    public class BranchController : Controller
    {
        private ILibraryBranch _branch;

        // create a constructor takes branchservice
        public BranchController(ILibraryBranch branch)
        {
            // save branchService param off into a private field 
            // to have access in the rest of the controller
            _branch = branch;
        }

        public IActionResult Index()
        {
            var branchModels = _branch.GetAll()
                .Select(br => new BranchDetailModel
                {
                    Id = br.Id,
                    BranchName = br.Name,
                    NumberOfAssets = _branch.GetAssetCount(br.LibraryAssets),
                    NumberOfPatrons = _branch.GetPatronCount(br.Patrons),
                    IsOpen = _branch.IsBranchOpen(br.Id)
                }).ToList();

            var model = new BranchIndexModel()
            {
                Branches = branchModels
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var branch = _branch.Get(id);
            var model = new BranchDetailModel
            {
                Id = branch.Id,
                BranchName = branch.Name,
                Description = branch.Description,
                Address = branch.Address,
                Telephone = branch.Telephone,
                BranchOpenedDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfPatrons = _branch.GetPatronCount(branch.Patrons),
                NumberOfAssets = _branch.GetAssetCount(branch.LibraryAssets),
                TotalAssetValue = _branch.GetAssetsValue(id),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branch.GetBranchHours(id)
            };

            return View(model);
        }
    }
}

LibraryProject/LibraryProject/Controllers/CatalogController.cs
using System.Linq;
using LibraryData;
using LibraryProject.Models.Catalog;
using LibraryProject.Models.Checkout;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryProject.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;
        private ICheckout _checkouts;
        public CatalogController(ILibraryAsset assets, ICheckout checkouts)
        {
            _assets = assets;
            _checkouts = checkouts;
        }

        public IActionResult Index()
        {
            var assetModels = _assets.GetAll();
            var listingResult = assetModels
                .Select(result => new AssetIndexListingModel
                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                    DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                    Title = result.Title,
                    Type = _assets.GetType(result.Id)
                });
            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var asset = _assets.GetById(id);

            var currentHolds = _checkouts.GetCurrentHolds(id)
                .Select(a=>new AssetHoldModel
                {
                    HoldPlaced = _checkouts.GetCurrentHoldPlaced(a.Id).ToString("d"),
                    PatronName = _checkouts.GetCurrentHoldPatronName(a.Id)
                });

            var model = new AssetDetailModel
            {
                AssetId = id,
                Title = asset.Title,
                Type = _assets.GetType(id),
                Year = asset.Year,
                Cost = asset.Cost,
                Status = asset.Status.Name,
                ImageUrl = asset.ImageUrl,
                AuthorOrDirector = _assets.GetAuthorOrDirector(id),
                CurrentLocation = _assets.GetCurrentLocation(id).Name,
                CheckoutHistory = _checkouts.GetCheckoutHistory(id),
                DeweyCallNumber = _assets.GetDeweyIndex(id),
                ISBN = _assets.GetIsbn(id),
                LatestCheckout = _checkouts.GetLatestCheckout(id),
                PatronName = _checkouts.GetCurrentCheckoutPatron(id),
                CurrentHolds = currentHolds
            };

            return View(model);
        }
        [Authorize]
        public IActionResult Checkout(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                IsCheckedOut = _checkouts.IsCheckedOut(id)
            };
            return View(model);
        }
        [Authorize]
        public IActionResult CheckIn(int id)
        {
            _checkouts.CheckInItem(id);
            return RedirectToAction("Detail", new { id = id });
        }
        [Authorize]
        public IActionResult MarkLost(int id)
        {
            _checkouts.MarkLost(id);
            return RedirectToAction("Detail", new { id = id });
        }
        [Authorize]
        public IActionResult MarkFound(int id)
        {
            _checkouts.MarkFound(id);
            return RedirectToAction("Detail", new { id = id });
        }
        [Authorize]
        public IActionResult Hold(int id)
        {
            var asset = _assets.GetById(id);

            var model = new CheckoutModel
            {
                AssetId = id,
                ImageUrl = asset.ImageUrl,
                Title = asset.Title,
                LibraryCardId = "",
                HoldCount = _checkouts.GetCurrentHolds(id).Count()
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult PlaceCheckout(int assetId, int libraryCardId)
        {
            _checkouts.CheckOutItem(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }

        [HttpPost]
        [Authorize]
        public IActionResult PlaceHold(int assetId, int libraryCardId)
        {
            _checkouts.PlaceHold(assetId, libraryCardId);
            return RedirectToAction("Detail", new { id = assetId });
        }
    }
}

LibraryProject/LibraryProject/Controllers/PatronController.cs
using System.Collections.Generic;
using System.Linq;
using LibraryData;
using LibraryData.Models;
using LibraryProject.Models.Patron;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryProject.Controllers
{
    public class PatronController : Controller
    {
        private IPatron _patron;

        // create a constructor takes branchservice
        public PatronController(IPatron patron)
        {
            // save branchService param off into a private field 
            // to have access in the rest of the controller
            _patron = patron;
        }
        [Authorize]
        public IActionResult Index()
        {
            var allPatrons = _patron.GetAll();

            var patronModels = allPatrons 
                .Select(p => new PatronDetailModel
                {
                    Id = p.Id,
                    LastName = p.LastName,
                    FirstName = p.FirstName,
                    LibraryCardId = p.LibraryCard.Id,
                    OverdueFees = p.LibraryCard.Fees,
                    HomeLibraryBranch = p.HomeLibraryBranch.Name
                }).ToList();

            var model = new PatronIndexModel()
            {
                Patrons = patronModels 
            };

            return View(model);
        }
        [Authorize]
        public IActionResult Detail(int id)
        {
            var patron = _patron.Get(id);

            var model = new PatronDetailModel
            {
                LastName = patron.LastName,
                FirstName = patron.FirstName,
                Address = patron.Adress,
                HomeLibraryBranch = patron.HomeLibraryBranch.Name,
                MemberSince = patron.LibraryCard.Created,
                OverdueFees = patron.LibraryCard.Fees,
                LibraryCardId = patron.LibraryCard.Id,
                Telephone = patron.TelephoneNumber,
                AssetsCheckedOut = _patron.GetCheckouts(id).ToList() ?? new List<Checkout>(),
                CheckoutHistory = _patron.GetCheckoutHistory(id),
                Holds = _patron.GetHolds(id)
            };

            return View(model);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

LibraryProject/LibraryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KGZ</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
    <link href=”//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css” rel=”stylesheet”>
    <link href="https://fonts.googleapis.com/css?family=Coda" rel="stylesheet">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />

</head>
<body onload="startTime()" style="background: #e8cfdb">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="custom-header mdl-layout__header mdl-layout__header--waterfall">
            <div class="mdl-layout__header-row">

                <!-- Title -->
                <span class="mdl-layout-title logo"><a href="/">Knjižnice Grada Zagreba</a></span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-controller="Catalog" asp-action="Index">Catalog</a>
                    <a class="mdl-navigation__link" asp-controller="Patron" asp-action="Index">Patrons</a>
                    <a class="mdl-navigation__link" asp-controller="Branch" asp-action="Index">Branches</a>
                    <!-- clock  -->
                    <a id="clockid" class="mdl-navigation__link  btn-warning text-dark font-weight-bold border-left"></a>
                    <pre>   </pre>
                    @await Html.PartialAsync("_LoginPartial")
                </nav>
            </div>
        </header>

        <div class="page-content">
            @RenderBody()
        </div>
    </div>
    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
    <script src="https://use.fontawesome.com/6110b02b27.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/clockjs.js"></script>


</body>
</html>